{
  lib,
  buildLinux,
  ...
} @ args:
let
  version = "6.19.0";

  _moreConfig = with lib.kernel; {
    NO_HZ_FULL = yes;
    NO_HZ_IDLE = no;
    CONTEXT_TRACKING_USER = yes;
    CONTEXT_TRACKING_USER_FORCE = yes;
    POSIX_AUX_CLOCKS = yes;

    BPF_SYSCALL = yes;
    BPF_JIT = yes;
    BPF_JIT_ALWAYS_ON = yes;
    BPF_JIT_DEFAULT_ON = yes;
    BPF_UNPRIV_DEFAULT_OFF = yes;

    PREEMPT_VOLUNTARY = no;
    PREEMPT_DYNAMIC = no;
    PREEMPT_LAZY = yes;
    SCHED_CORE = yes;

    BSD_PROCESS_ACCT = no;
    TASKSTATS = no;
    VIRT_CPU_ACCOUNTING = yes;
    VIRT_CPU_ACCOUNTING_GEN = yes;
    PSI = yes;
    PSI_DEFAULT_DISABLED = no;

    # PREEMPT_RCU = no;
    RCU_NOCB_CPU = yes;
    RCU_NOCB_CPU_DEFAULT_ALL = yes;
    RCU_LAZY = yes;
    RCU_LAZY_DEFAULT_OFF = no;

    IKCONFIG = yes;
    IKCONFIG_PROC = yes;

    UCLAMP_TASK = yes;
    # UCLAMP_BUCKETS_COUNT = freeform 5; # default
    NUMA_BALANCING = yes;
    NUMA_BALANCING_DEFAULT_ENABLED = yes;
    SLAB_OBJ_EXT = yes;
    MEMCG = yes;
    CGROUP_WRITEBACK = yes;
    GROUP_SCHED_BANDWIDTH = yes;
    CFS_BANDWIDTH = yes;
    RT_GROUP_SCHED = yes;
    UCLAMP_TASK_GROUP = no;
    CGROUP_DMEM = yes;
    CGROUP_BPF = yes;
    USER_NS = yes;
    CHECKPOINT_RESTORE = yes;
    SCHED_AUTOGROUP = yes;

    RD_GZIP = no;
    RD_BZIP2 = no;
    RD_LZMA = no;
    RD_XZ = no;
    RD_LZO = no;
    RD_LZ4 = no;
    RD_ZSTD = yes;

    EXPERT = yes;
    BASE_SMALL = no;
    IO_URING_MOCK_FILE = no;
    RSEQ_STATS = no;
    RSEQ_DEBUG_DEFAULT_ENABLE = no;

    # SYSTEM_DATA_VERIFICATION = no;
    KEXEC_FILE = yes;
    KEXEC_SIG = yes;
    KEXEC_SIG_FORCE = no;

    X86_X2APIC = no;
    X86_CPU_RESCTRL = yes;
    X86_AMD_PLATFORM_DEVICE = no;
    PARAVIRT = no;
    ARCH_CPUIDLE_HALTPOLL = no;
    PROCESSOR_SELECT = yes;
    CPU_SUP_INTEL = no;
    CPU_SUP_AMD = yes;
    CPU_SUP_HYGON = no;
    CPU_SUP_CENTAUR = no;
    CPU_SUP_ZHAOXIN = no;

    X86_MSR = no;
    X86_CPUID = no;
    MTRR = no;
    EFI_HANDOVER_PROTOCOL = no;
    EFI_MIXED = no;
    RANDOMIZE_BASE = no;
    LEGACY_VSYSCALL_XONLY = no;
    LEGACY_VSYSCALL_NONE = yes;
    X86_BUS_LOCK_DETECT = no;

    MITIGATION_SLS = yes;

    SUSPEND_SKIP_SYNC = no;
    HIBERNATION = no;
    PM_DEBUG = no;
    ENERGY_MODEL = yes;
    ACPI_FPDT = yes;
    ACPI_HED = yes;
    ACPI_NFIT = yes;
    NFIT_SECURITY_DEBUG = no;
    ACPI_HMAT = yes;
    ACPI_APEI = yes;
    ACPI_APEI_GHES = yes;
    ACPI_APEI_EINJ = no;
    ACPI_APEI_ERST_DEBUG = no;
    ACPI_PFRUT = yes;
    ACPI_FFH = yes;

    CPU_FREQ_GOV_POWERSAVE = yes;
    CPU_FREQ_GOV_ONDEMAND = no;
    X86_INTEL_PSTATE = no;
    X86_PCC_CPUFREQ = yes;
    CPU_IDLE_GOV_TEO = yes;

    ISA_BUS = no;
    X86_X32_ABI = yes;
    KVM_X86 = yes;
    KVM = yes;
    KVM_AMD = yes;
    KVM_IOAPIC = yes;
    KVM_SMM = yes;
    KVM_HYPERV = yes;
    KVM_XEN = no;
    KVM_PROVE_MMU = no;
    # KVM_MAX_NR_VCPUS = freeform "256"; repeated question?

    STACKPROTECTOR_STRONG = no;
    RANDOMIZE_KSTACK_OFFSET_DEFAULT = yes;
    GCC_PLUGINS = no;

    MODULE_COMPRESS = yes;
    MODULE_COMPRESS_GZIP = no;
    MODULE_COMPRESS_XZ = no;
    MODULE_COMPRESS_ZSTD = yes;
    MODULE_COMPRESS_ALL = yes;
    MODULE_DECOMPRESS = yes;

    BLK_CGROUP_RWSTAT = yes;
    BLK_ICQ = yes;
    BLK_DEV_BSGLIB = yes;
    BLK_DEV_INTEGRITY = yes;
    BLK_DEV_ZONED = yes;
    BLK_DEV_THROTTLING = yes;
    BLK_WBT = yes;
    BLK_WBT_MQ = yes;
    BLK_INLINE_ENCRYPTION = yes;
    BLK_INLINE_ENCRYPTION_FALLBACK = yes;
    DM_CRYPT = yes;

    PARTITION_ADVANCED = yes;
    ACORN_PARTITION = no;
    AIX_PARTITION = no;
    OSF_PARTITION = no;
    AMIGA_PARTITION = no;
    ATARI_PARTITION = no;
    MAC_PARTITION = no;
    MSDOS_PARTITION = yes;

    BSD_DISKLABEL = no;
    MINIX_SUBPARTITION = no;
    SOLARIS_X86_PARTITION = no;
    UNIXWARE_DISKLABEL = no;
    LDM_PARTITION = no;
    SGI_PARTITION = no;
    ULTRIX_PARTITION = no;
    SUN_PARTITION = no;
    KARMA_PARTITION = no;
    # EFII_PARTITION = yes;
    SYSV68_PARTITION = no;
    CMDLINE_PARTITION = no;

    IOSCHED_BFQ = yes;
    BFQ_GROUP_IOSCHED = yes;
    BFQ_CGROUP_DEBUG = no;

    PREEMPT_NOTIFIERS = yes;

    SLUB_TINY = no;
    MEMORY_ISOLATION = yes;
    PAGE_REPORTING = yes;
    KSM = yes;
    PERSISTENT_HUGE_ZERO_FOLIO = yes;
    MM_ID = yes;
    TRANSPARENT_HUGEPAGE = yes;
    TRANSPARENT_HUGEPAGE_ALWAYS = yes;
    TRANSPARENT_HUGEPAGE_SHMEM_HUGE_NEVER = yes;
    TRANSPARENT_HUGEPAGE_TMPFS_HUGE_NEVER = yes;
    READ_ONLY_THP_FOR_FS = no;
    NO_PAGE_MAPCOUNT = no;
    CMA = yes;
    CMA_DEBUGFS = no;
    CMA_SYSFS = no;
    CMA_AREAS = freeform "20";
    PAGE_IDLE_FLAG = yes;
    IDLE_PAGE_TRACKING = yes;
    HMM_MIRROR = yes;
    HAVE_ARCH_USERFAULTFD_WP = yes;
    HAVE_ARCH_USERFAULTFD_MINOR = yes;
    USERFAULTFD = yes;
    PTE_MARKER_UFFD_WP = yes;

    DAMON = yes;
    DAMON_VADDR = yes;
    DAMON_PADDR = yes;
    DAMON_SYSFS = yes;
    DAMON_RECLAIM = yes;
    DAMON_LRU_SORT = yes;
    DAMON_STAT = yes;
    DAMON_STAT_ENABLED_DEFAULT = yes;

    SKB_DECRYPTED = yes;
    NET_DEVMEM = yes;

    TLS = module;
    TLS_DEVICE = yes;

    HAMRADIO = no;
    CAN = no;
    BT = no;
    AF_RXRPC = no;
    AF_KCM = no;
    MCTP = no;
    FIB_RULES = yes;
    WIRELESS = no;
    RFKILL = no;
    NET_9P = no;
    CAIF = no;
    CEPH_LIB = no;
    NFC = no;
    PSAMPLE = no;
    NET_IFE = no;
    LWTUNNEL = yes;
    SOCK_VALIDATE_XMIT = yes;
    NET_SOCK_MSG = yes;
    PAGE_POOL = yes;
    PAGE_POOL_STATS = no;

    PCIEAER = yes;
    PCIEAER_INJECT = no;
    PCIE_ECRC = no;
    PCIE_DPC = yes;
    PCIE_PTM = yes;
    PCIE_EDR = yes;
    PCI_IDE = yes;
    PCI_TSM = yes;
    PCI_DOE = yes;
    PCI_IOV = yes;
    PCI_NPEM = yes;
    PCIE_BUS_DEFAULT = yes;

    PCCARD = no;

    DEV_COREDUMP = yes;
    HMEM_REPORTING = yes;
    REGMAP_I2C = module;
    REGMAP_MMIO = yes;
    SYSFB = yes;
    EFI_VARS_PSTORE = yes;
    EFI_SOFT_RESERVE = yes;
    EFI_DEV_PATH_PARSER = yes;
    APPLE_PROPERTIES = yes;
    UEFI_CPER = yes;
    UEFI_CPER_X86 = yes;

    FWCTL = yes;
    NVME_KEYRING = yes;
    NVME_AUTH = yes;
    NVME_CORE = yes;
    BLK_DEV_NVME = yes;
    NVME_MULTIPATH = yes;
    NVME_VERBOSE_ERRORS = yes;
    NVME_HWMON = yes;
    NVME_HOST_AUTH = yes;

    MISC_RTSX = yes;
    NTSYNC = yes;
    INTEL_MEI = no;
    MISC_RTSX_USB = yes;

    ATA = no;

    MACINTOSH_DRIVERS = no;
    NET_VENDOR_ADI = yes;
    NET_VENDOR_QUALCOMM = yes;
    NET_VENDOR_REALTEK = yes;

    NET_VENDOR_3COM = no;
    NET_VENDOR_ADAPTEC = no;
    NET_VENDOR_AGERE = no;
    NET_VENDOR_ALACRITECH = no;
    NET_VENDOR_ALTEON = no;
    NET_VENDOR_AMAZON = no;
    NET_VENDOR_AMD = no;
    NET_VENDOR_AQUANTIA = no;
    NET_VENDOR_ARC = no;
    NET_VENDOR_ASIX = no;
    NET_VENDOR_ATHEROS = no;
    NET_VENDOR_CADENCE = no;
    NET_VENDOR_CAVIUM = no;
    NET_VENDOR_CHELSIO = no;
    NET_VENDOR_CISCO = no;
    NET_VENDOR_CORTINA = no;
    NET_VENDOR_DAVICOM = no;
    NET_VENDOR_DEC = no;
    NET_VENDOR_DLINK = no;
    NET_VENDOR_EMULEX = no;
    NET_VENDOR_ENGLEDER = no;
    NET_VENDOR_EZCHIP = no;
    NET_VENDOR_FUNGIBLE = no;
    NET_VENDOR_GOOGLE = no;
    NET_VENDOR_HISILICON = no;
    NET_VENDOR_HUAWEI = no;
    NET_VENDOR_INTEL = no;
    NET_VENDOR_LITEX = no;
    NET_VENDOR_MARVELL = no;
    NET_VENDOR_MELLANOX = no;
    NET_VENDOR_META = no;
    NET_VENDOR_MICREL = no;
    NET_VENDOR_MICROCHIP = no;
    NET_VENDOR_MICROSEMI = no;
    NET_VENDOR_MICROSOFT = no;
    NET_VENDOR_MUCSE = no;
    NET_VENDOR_MYRI = no;
    NET_VENDOR_NI = no;
    NET_VENDOR_NATSEMI = no;
    NET_VENDOR_NETERION = no;
    NET_VENDOR_NETRONOME = no;
    NET_VENDOR_NVIDIA = no;
    NET_VENDOR_OKI = no;
    NET_VENDOR_PACKET_ENGINES = no;
    # NET_VENDOR_PELSANDO = no;
    NET_VENDOR_QLOGIC = no;
    NET_VENDOR_BROCADE = no;
    NET_VENDOR_RDC = no;
    NET_VENDOR_RENESAS = no;
    NET_VENDOR_ROCKER = no;
    NET_VENDOR_SAMSUNG = no;
    NET_VENDOR_SEEQ = no;
    NET_VENDOR_SILAN = no;
    NET_VENDOR_SIS = no;
    NET_VENDOR_SOLARFLARE = no;
    NET_VENDOR_SMSC = no;
    NET_VENDOR_SOCIONEXT = no;
    NET_VENDOR_STMICRO = no;
    NET_VENDOR_SUN = no;
    # NET_VENDOR_SYNOPSIS = no;
    NET_VENDOR_TEHUTI = no;
    NET_VENDOR_TI = no;
    NET_VENDOR_VERTEXCOM = no;
    NET_VENDOR_VIA = no;
    NET_VENDOR_WANGXUN = no;
    NET_VENDOR_WIZNET = no;
    NET_VENDOR_XILINX = no;

    USB_RTL8150 = module;
    USB_RTL8152 = module;
    USB_IPHETH = yes;

    WLAN = no;
    KEYBOARD_XTKBD = yes;
    JOYSTICK_XPAD = module;
    JOYSTICK_XPAD_FF = yes;
    JOYSTICK_XPAD_LEDS = yes;
    TABLET_SERIAL_WACOM4 = module;
    TOUCHSCREEN_WACOM_W8001 = module;
    TOUCHSCREEN_WACOM_I2C = module;
    INPUT_PCSPKR = yes;
    SERIAL_8250_16550A_VARIANTS = yes;
    SERIAL_8250_FINTEK = yes;

    I2C_CHARDEV = yes;
    I2C_MUX = yes;
    I2C_AMD756 = yes;
    I2C_AMD8111 = yes;
    I2C_AMD_MP2 = yes;
    I2C_VIRTIO = yes;
    I3C = yes;
    SPI = yes;
    SPI_MASTER = yes;
    SPI_MEM = yes;
    SPI_AMD = yes;
    SPI_DYNAMIC = yes;
    PINCTRL = yes;

    WATCHDOG = no;
    REGULATOR = yes;
    REGULATOR_FIXED_VOLTAGE = yes;
    REGULATOR_VIRTUAL_CONSUMER = yes;
    REGULATOR_USERSPACE_CONSUMER = yes;
    CEC_CORE = yes;
    MEDIA_CEC_SUPPORT = yes;

    AGP = no;
    DRM_DRAW = yes;
    DRM_PANIC = yes;
    DRM_PANIC_SCREEN = freeform "kmsg";
    DRM_DISPLAY_DP_AUX_CEC = yes;
    DRM_DISPLAY_DP_AUX_CHARDEV = yes;
    DRM_EXEC = yes;
    DRM_GPUVM = yes;
    DRM_GPUSVM = yes;
    DRM_TTM_HELPER = yes;
    DRM_SUBALLOC_HELPER = yes;
    DRM_SCHED = yes;
    DRM_I915 = no;
    DRM_SYSFB_HELPER = yes;
    DRM_EFIDRM = yes;
    DRM_VIRTIO_GPU = no;
    DRM_XE = yes;
    DRM_ACCEL = yes;

    SND_DYNAMIC_MINORS = yes;
    SND_MAX_CARDS = freeform "16";
    SND_CTL_LED = yes;
    SND_HDA_RECONFIG = yes;
    SND_HDA_GENERIC_LEDS = yes;
    SND_HDA_GENERIC = yes;
    SND_HDA_CODEC_REALTEK = yes;
    SND_HDA_CODEC_REALTEK_LIB = yes;
    SND_HDA_CODEC_ALC260 = yes;
    SND_HDA_CODEC_ALC262 = yes;
    SND_HDA_CODEC_ALC268 = yes;
    SND_HDA_CODEC_ALC269 = yes;
    SND_HDA_CODEC_ALC662 = yes;
    SND_HDA_CODEC_ALC680 = yes;
    SND_HDA_CODEC_ALC861 = yes;
    SND_HDA_CODEC_ALC861VD = yes;
    SND_HDA_CODEC_ALC880 = yes;
    SND_HDA_CODEC_ALC882 = yes;
    SND_HDA_CODEC_HDMI = yes;
    SND_HDA_CODEC_HDMI_GENERIC = yes;
    SND_HDA_CODEC_HDMI_SIMPLE = yes;
    SND_HDA_CODEC_HDMI_INTEL = yes;
    SND_HDA_SCODEC_COMPONENT = yes;

    HID_A4TECH = no;
    HID_APPLE = no;
    HID_BELKIN = no;
    HID_CHERRY = no;
    HID_CHICONY = no;
    HID_CYPRESS = no;
    HID_EZKEY = no;
    HID_GYRATION = no;
    HID_ITE = no;
    HID_KENSINGTON = no;
    HID_REDRAGON = no;
    HID_MONTEREY = no;
    HID_MULTITOUCH = yes;
    HID_NTRIG = no;
    HID_PANTHERLORD = no;
    HID_SAMSUNG = no;
    SONY_FF = yes;
    HID_STEAM = module;
    STEAM_FF = yes;
    HID_WACOM = module;

    AMD_SFH_HID = yes;
    USB_LED_TRIG = yes;
    USB_ULPI_BUS = yes;
    USB_OTG = yes;
    USB_LEDS_TRIGGER_USBPORT = yes;
    USB_XHCI_SIDEBAND = yes;
    USB_EHCI_ROOT_HUB_TT = yes;
    USB_EHCI_FSL = yes;
    USB_EHCI_HCD_PLATFORM = yes;
    USB_STORAGE_REALTEK = module;
    USB_UAS = module;

    USBIP_CORE = module;
    USBIP_VHCI_HCD = module;
    USBIP_VHCI_HC_PORTS = freeform "8";
    USBIP_VHCI_NR_HCS = freeform "1";
    USBIP_HOST = module;

    USB_SERIAL = yes;
    USB_SERIAL_GENERIC = yes;
    USB_SERIAL_SIMPLE = yes;
    APPLE_MFI_FASTCHARGE = module;
    USB_GADGET = module;
    # USB_GADGET_VBUS_DRAW = freeform 2;
    # USB_GADGET_STORAGE_NUM_BUFFERS = freeform 2;
    TYPEC = module;
    TYPEC_TCPM = module;
    TYPEC_TCPCI = module;
    TYPEC_RT1711H = module;
    TYPEC_TCPCI_MAXIM = module;
    TYPEC_UCSI = module;
    UCSI_CCG = module;
    UCSI_ACPI = module;
    UCSI_STM32G0 = module;
    TYPEC_TPS6598X = module;
    TYPEC_ANX7411 = module;
    TYPEC_RT1719 = module;
    TYPEC_HD3SS3220 = module;
    TYPEC_STUSB160X = module;
    TYPEC_WUSB3801 = module;
    TYPEC_MUX_FSA4480 = module;
    TYPEC_MUX_GPIO_SBU = module;
    TYPEC_MUX_PI3USB30532 = module;
    TYPEC_MUX_IT5205 = module;
    TYPEC_MUX_NB7VPQ904M = module;
    TYPEC_MUX_PS883X = module;
    TYPEC_MUX_PTN36502 = module;
    TYPEC_MUX_TUSB1046 = module;
    TYPEC_MUX_WCD939X_USBSS = module;
    TYPEC_TBT_ALTMODE = module;
    USB_ROLE_SWITCH = module;
    MMC = yes;
    MMC_BLOCK = yes;
    # MMC_BLOCK_MINORS = freeform 8;
    SCSI_UFSHCD = module;
    SCSI_UFS_BSG = yes;
    SCSI_UFS_CRYPTO = yes;
    SCSI_UFS_HWMON = yes;
    LEDS_CLASS_FLASH = module;
    LEDS_CLASS_MULTICOLOR = yes;
    LEDS_BRIGHTNESS_HW_CHANGED = yes;

    LEDS_APU = module;
    LEDS_AW200XX = module;
    LEDS_LM3530 = module;
    LEDS_LM3532 = module;
    LEDS_LM3642 = module;
    LEDS_PCA9532 = module;
    LEDS_LP3944 = module;
    LEDS_LP50XX = module;
    LEDS_PCA955X = module;
    LEDS_PCA963X = module;
    LEDS_PCA995X = module;
    LEDS_DAC124S085 = module;
    LEDS_REGULATOR = module;
    LEDS_BD2606MVV = module;
    LEDS_BD2802 = module;
    LEDS_INTEL_SS4200 = module;
    LEDS_TCA6507 = module;
    LEDS_TLC591XX = module;
    LEDS_LM355x = module;
    LEDS_IS31FL319X = module;
    LEDS_BLINKM = module;
    LEDS_BLINKM_MULTICOLOR = yes;
    LEDS_MLXCPLD = module;
    LEDS_MLXREG = module;
    LEDS_USER = module;
    LEDS_NIC78BX = module;
    LEDS_SPI_BYTE = module;
    LEDS_AS3645A = module;
    LEDS_LM3601X = module;
    LEDS_SGM3140 = module;
    LEDS_KTD202X = module;

    EDAC = yes;
    EDAC_DECODE_MCE = yes;
    EDAC_SCRUB = yes;
    EDAC_ECS = yes;
    EDAC_MEM_REPAIR = yes;
    EDAC_AMD64 = yes;

    AMD_AE4DMA = yes;
    AMD_PTDMA = yes;
    AMD_QDMA = yes;

    IRQ_BYPASS_MANAGER = yes;
    TSM = yes;
    VHOST_TASK = yes;

    SURFACE_PLATFORMS = no;
    GIGABYTE_WMI = yes;
    EEEPC_LAPTOP = no;

    HAVE_CLK = yes;
    HAVE_CLK_PREPARE = yes;
    COMMON_CLK = yes;
    HWSPINLOCK = yes;

    PM_DEVFREQ = yes;
    DEVFREQ_GOV_SIMPLE_ONDEMAND = yes;
    EXTCON = yes;
    MEMORY = yes;
    PWM = yes;

    RAS = yes;
    USB4 = yes;
    USB4_PCIE_TUNNELING = yes;

    LIBNVDIMM = yes;
    BLK_DEV_PMEM = yes;
    ND_CLAIM = yes;
    ND_BTT = yes;
    DAX = yes;
    PM_OPP = yes;
    HTE = yes;

    BTRFS_FS = yes;
    BTRFS_FS_POSIX_ACL = yes;
    FS_ENCRYPTION = yes;
    FS_ENCRYPTION_ALGS = yes;
    FS_ENCRYPTION_INLINE_CRYPT = yes;
    UDF_FS = yes;
    EXFAT_FS = yes;
    EXFAT_DEFAULT_IOCHARSET = freeform "utf8";
    NTFS3_FS = yes;
    PROC_CHILDREN = yes;
    PROC_CPU_RESCTRL = yes;
    EFIVAR_FS = yes;
    RESCTRL_FS = yes;
    RESCTRL_FS_PSEUDO_LOCK = yes;
    PSTORE = yes;
    PSTORE_DEFAULT_KMSG_BYTES = freeform "10240";
    PSTORE_COMPRESS = yes;
    NETWORK_FILESYSTEMS = no;

    SECURITY_DMESG_RESTRICT = yes;
    PROC_MEM_ALWAYS_FORCE = no;
    PROC_MEM_NO_FORCE = yes;
    SECURITYFS = yes;
    INTEGRITY = no;
    ZERO_CALL_USED_REGS = yes;
    HARDENED_USERCOPY = yes;
    HARDENED_USERCOPY_DEFAULT_ON = yes;
    LIST_HARDENED = yes;
    BUG_ON_DATA_CORRUPTION = yes;

    CRYPTO_ALGAPI = yes;
    CRYPTO_ALGAPI2 = yes;
    CRYPTO_AEAD = yes; # module
    CRYPTO_AEAD2 = yes;
    CRYPTO_SIG = yes;
    CRYPTO_SIG2 = yes;
    CRYPTO_SKCIPHER = yes;
    CRYPTO_SKCIPHER2 = yes;
    CRYPTO_HASH = yes;
    CRYPTO_HASH2 = yes;
    CRYPTO_RNG = yes;
    CRYPTO_RNG2 = yes;
    CRYPTO_RNG_DEFAULT = yes;
    CRYPTO_AKCIPHER2 = yes;
    CRYPTO_AKCIPHER = yes;
    CRYPTO_KPP2 = yes;
    CRYPTO_KPP = yes;
    CRYPTO_ACOMP2 = yes;
    CRYPTO_HKDF = yes; # module
    CRYPTO_MANAGER = yes;
    CRYPTO_MANAGER2 = yes;
    CRYPTO_USER = yes; # module
    CRYPTO_NULL = yes; # module
    CRYPTO_PCRYPT = yes; # module
    CRYPTO_CRYPTD = yes; # module
    CRYPTO_AUTHENC = yes; # module
    CRYPTO_KRB5ENC = yes; # module
    CRYPTO_BENCHMARK = yes; # module
    CRYPTO_ENGINE = yes; # module
    CRYPTO_RSA = yes;
    CRYPTO_DH = yes;
    CRYPTO_DH_RFC7919_GROUPS = yes;
    CRYPTO_ECC = yes; # module
    CRYPTO_ECDH = yes; # module
    CRYPTO_ECDSA = yes; # module
    CRYPTO_ECRDSA = yes; # module
    CRYPTO_AES = yes;
    CRYPTO_AES_TI = yes; # module
    CRYPTO_ANUBIS = yes; # module
    CRYPTO_ARIA = yes; # module
    CRYPTO_BLOWFISH = yes; # module
    CRYPTO_BLOWFISH_COMMON = yes; # module
    CRYPTO_CAMELLIA = yes; # module
    CRYPTO_CAST_COMMON = yes; # module
    CRYPTO_CAST5 = yes; # module
    CRYPTO_CAST6 = yes; # module
    CRYPTO_DES = yes; # module
    CRYPTO_FCRYPT = yes; # module
    CRYPTO_KHAZAD = yes; # module
    CRYPTO_SEED = yes; # module
    CRYPTO_SERPENT = yes; # module
    CRYPTO_SM4 = yes; # module
    CRYPTO_SM4_GENERIC = yes; # module
    CRYPTO_TEA = yes; # module
    CRYPTO_TWOFISH = yes; # module
    CRYPTO_TWOFISH_COMMON = yes; # module
    CRYPTO_ADIANTUM = yes; # module
    CRYPTO_ARC4 = yes; # module
    CRYPTO_CHACHA20 = yes; # module
    CRYPTO_CBC = yes; # module
    CRYPTO_CTR = yes;
    CRYPTO_CTS = yes; # module
    CRYPTO_ECB = yes;
    CRYPTO_HCTR2 = yes; # module
    CRYPTO_LRW = yes; # module
    CRYPTO_PCBC = yes; # module
    CRYPTO_XCTR = yes; # module
    CRYPTO_XTS = yes; # module
    CRYPTO_NHPOLY1305 = yes; # module
    CRYPTO_AEGIS128 = yes; # module
    CRYPTO_CHACHA20POLY1305 = yes; # module
    CRYPTO_CCM = yes; # module
    CRYPTO_GCM = yes; # module
    CRYPTO_GENIV = yes; # module
    CRYPTO_SEQIV = yes; # module
    CRYPTO_ECHAINIV = yes; # module
    CRYPTO_ESSIV = yes; # module
    CRYPTO_BLAKE2B = yes; # module
    CRYPTO_CMAC = yes; # module
    CRYPTO_GHASH = yes; # module
    CRYPTO_HMAC = yes;
    CRYPTO_MD4 = yes; # module
    CRYPTO_MD5 = yes; # module
    CRYPTO_MICHAEL_MIC = yes; # module
    CRYPTO_RMD160 = yes; # module
    CRYPTO_SHA1 = yes; # module
    CRYPTO_SHA256 = yes;
    CRYPTO_SHA512 = yes;
    CRYPTO_SHA3 = yes;
    CRYPTO_SM3_GENERIC = yes; # module
    CRYPTO_STREEBOG = yes; # module
    CRYPTO_WP512 = yes; # module
    CRYPTO_XCBC = yes; # module
    CRYPTO_XXHASH = yes; # module
    CRYPTO_CRC32C = yes; # module
    CRYPTO_CRC32 = yes; # module
    CRYPTO_DEFLATE = yes; # module
    CRYPTO_LZO = yes;
    CRYPTO_842 = yes; # module
    CRYPTO_LZ4 = yes; # module
    CRYPTO_LZ4HC = yes; # module
    CRYPTO_ZSTD = yes;
    CRYPTO_DRBG_MENU = yes;
    CRYPTO_DRBG_HMAC = yes;
    CRYPTO_DRBG_HASH = yes;
    CRYPTO_DRBG_CTR = yes;
    CRYPTO_DRBG = yes;
    CRYPTO_JITTERENTROPY = yes;
    # CRYPTO_JITTERENTROPY_MEMORY_BLOCKS=64
    # CRYPTO_JITTERENTROPY_MEMORY_BLOCKSIZE=32
    # CRYPTO_JITTERENTROPY_OSR=1
    CRYPTO_DF80090A = yes;
    CRYPTO_USER_API = yes; # module
    CRYPTO_USER_API_HASH = yes; # module
    CRYPTO_USER_API_SKCIPHER = yes; # module
    CRYPTO_USER_API_RNG = yes; # module
    CRYPTO_USER_API_AEAD = yes; # module
    CRYPTO_USER_API_ENABLE_OBSOLETE = yes;
    CRYPTO_AES_NI_INTEL = yes; # module
    CRYPTO_BLOWFISH_X86_64 = yes; # module
    CRYPTO_CAMELLIA_X86_64 = yes; # module
    CRYPTO_CAMELLIA_AESNI_AVX_X86_64 = yes; # module
    CRYPTO_CAMELLIA_AESNI_AVX2_X86_64 = yes; # module
    CRYPTO_CAST5_AVX_X86_64 = yes; # module
    CRYPTO_CAST6_AVX_X86_64 = yes; # module
    CRYPTO_DES3_EDE_X86_64 = yes; # module
    CRYPTO_SERPENT_SSE2_X86_64 = yes; # module
    CRYPTO_SERPENT_AVX_X86_64 = yes; # module
    CRYPTO_SERPENT_AVX2_X86_64 = yes; # module
    CRYPTO_SM4_AESNI_AVX_X86_64 = yes; # module
    CRYPTO_SM4_AESNI_AVX2_X86_64 = yes; # module
    CRYPTO_TWOFISH_X86_64 = yes; # module
    CRYPTO_TWOFISH_X86_64_3WAY = yes; # module
    CRYPTO_TWOFISH_AVX_X86_64 = yes; # module
    CRYPTO_ARIA_AESNI_AVX_X86_64 = yes; # module
    CRYPTO_ARIA_AESNI_AVX2_X86_64 = yes; # module
    CRYPTO_ARIA_GFNI_AVX512_X86_64 = yes; # module
    CRYPTO_AEGIS128_AESNI_SSE2 = yes; # module
    CRYPTO_NHPOLY1305_SSE2 = yes; # module
    CRYPTO_NHPOLY1305_AVX2 = yes; # module
    CRYPTO_SM3_AVX_X86_64 = yes; # module
    CRYPTO_GHASH_CLMUL_NI_INTEL = yes; # module
    CRYPTO_HW = yes;
    CRYPTO_DEV_PADLOCK = yes; # module
    CRYPTO_DEV_PADLOCK_AES = yes; # module
    CRYPTO_DEV_PADLOCK_SHA = yes; # module
    CRYPTO_DEV_ATMEL_I2C = yes; # module
    CRYPTO_DEV_ATMEL_ECC = yes; # module
    CRYPTO_DEV_ATMEL_SHA204A = yes; # module
    CRYPTO_DEV_CCP = yes;
    CRYPTO_DEV_CCP_DD = yes; # module
    CRYPTO_DEV_SP_CCP = yes;
    CRYPTO_DEV_CCP_CRYPTO = yes; # module
    CRYPTO_DEV_SP_PSP = yes;
    CRYPTO_DEV_NITROX = yes; # module
    CRYPTO_DEV_NITROX_CNN55XX = yes; # module
    CRYPTO_DEV_QAT = yes; # module
    CRYPTO_DEV_QAT_DH895xCC = yes; # module
    CRYPTO_DEV_QAT_C3XXX = yes; # module
    CRYPTO_DEV_QAT_C62X = yes; # module
    CRYPTO_DEV_QAT_4XXX = yes; # module
    CRYPTO_DEV_QAT_420XX = yes; # module
    CRYPTO_DEV_QAT_6XXX = yes; # module
    CRYPTO_DEV_QAT_DH895xCCVF = yes; # module
    CRYPTO_DEV_QAT_C3XXXVF = yes; # module
    CRYPTO_DEV_QAT_C62XVF = yes; # module
    CRYPTO_DEV_VIRTIO = yes; # module
    CRYPTO_DEV_SAFEXCEL = yes; # module
    CRYPTO_DEV_AMLOGIC_GXL = yes; # module
    ASYMMETRIC_KEY_TYPE = yes;
    ASYMMETRIC_PUBLIC_KEY_SUBTYPE = yes;
    X509_CERTIFICATE_PARSER = yes;
    PKCS8_PRIVATE_KEY_PARSER = yes; # module
    PKCS7_MESSAGE_PARSER = yes;
    FIPS_SIGNATURE_SELFTEST = yes; # module
    FIPS_SIGNATURE_SELFTEST_RSA = yes;
    FIPS_SIGNATURE_SELFTEST_ECDSA = yes;
    SYSTEM_TRUSTED_KEYRING = yes;
    # SYSTEM_TRUSTED_KEYS=""
    CRYPTO_KRB5 = yes; # module
    BINARY_PRINTF = yes;
    RAID6_PQ = yes; # module
    RAID6_PQ_BENCHMARK = yes;
    LINEAR_RANGES = yes;
    PACKING = yes;
    BITREVERSE = yes;
    GENERIC_STRNCPY_FROM_USER = yes;
    GENERIC_STRNLEN_USER = yes;
    GENERIC_NET_UTILS = yes;
    CORDIC = yes; # module
    PRIME_NUMBERS = yes; # module
    RATIONAL = yes;
    GENERIC_IOMAP = yes;
    ARCH_USE_CMPXCHG_LOCKREF = yes;
    ARCH_HAS_FAST_MULTIPLIER = yes;
    ARCH_USE_SYM_ANNOTATIONS = yes;
    CRC8 = yes; # module
    CRC16 = yes;
    CRC_CCITT = yes;
    CRC_ITU_T = yes; # module
    CRC_T10DIF = yes;
    CRC_T10DIF_ARCH = yes;
    CRC32 = yes;
    CRC32_ARCH = yes;
    CRC64 = yes;
    CRC64_ARCH = yes;
    CRC_OPTIMIZATIONS = yes;
    CRYPTO_HASH_INFO = yes;
    CRYPTO_LIB_UTILS = yes;
    CRYPTO_LIB_AES = yes;
    # CRYPTO_LIB_AESGCM = yes;
    CRYPTO_LIB_ARC4 = yes; # module
    CRYPTO_LIB_GF128MUL = yes;
    CRYPTO_LIB_BLAKE2B = yes; # module
    CRYPTO_LIB_BLAKE2S_ARCH = yes;
    CRYPTO_LIB_CHACHA = yes; # module
    CRYPTO_LIB_CHACHA_ARCH = yes;
    CRYPTO_LIB_DES = yes; # module
    CRYPTO_LIB_MD5 = yes;
    CRYPTO_LIB_POLY1305_ARCH = yes;
    CRYPTO_LIB_POLY1305_GENERIC = yes;
    # CRYPTO_LIB_POLY1305_RSIZE=11
    CRYPTO_LIB_POLYVAL = yes; # module
    CRYPTO_LIB_POLYVAL_ARCH = yes;
    # CRYPTO_LIB_CHACHA20POLY1305 = yes; # module
    CRYPTO_LIB_SHA1 = yes;
    CRYPTO_LIB_SHA1_ARCH = yes;
    CRYPTO_LIB_SHA256 = yes;
    CRYPTO_LIB_SHA256_ARCH = yes;
    CRYPTO_LIB_SHA512 = yes;
    CRYPTO_LIB_SHA512_ARCH = yes;
    CRYPTO_LIB_SHA3 = yes;
    CRYPTO_LIB_SM3 = yes; # module

    ZSTD_COMPRESS = yes;

    SWIOTLB_DYNAMIC = yes;
    DMA_CMA = yes;
    DMA_NUMA_CMA = yes;

    FONT_8x8 = yes;
    MEMREGION = yes;
    MAGIC_SYSRQ = no;
    SLUB_DEBUG = no;
    DEBUG_STACK_USAGE = no;
    LOCKUP_DETECTOR = yes;
    SOFTLOCKUP_DETECTOR = yes;
    HARDLOCKUP_DETECTOR = yes;
    HARDLOCKUP_DETECTOR_PERF = yes;
    HARDLOCKUP_DETECTOR_COUNTS_HRTIMER = yes;
    RCU_TRACE = no;
    BPF_EVENTS = yes;
    PROVIDE_OHCI1394_DMA_INIT = no;
    IO_STRICT_DEVMEM = yes;
    EFI_PGT_DUMP = yes;
    X86_DEBUG_FPU = no;
    RUNTIME_TESTING_MENU = no;

    PACKET = yes;
    PACKET_DIAG = yes;
    UNIX = yes;
    AF_UNIX_OOB = yes;
    UNIX_DIAG = yes;
    XFRM = yes;
    XFRM_OFFLOAD = yes;
    XFRM_ALGO = yes;
    XFRM_USER = yes;
    XFRM_USER_COMPAT = yes;
    XFRM_INTERFACE = yes;
    XFRM_AH = yes;
    XFRM_ESP = yes;
    XFRM_IPCOMP = yes;
    NET_KEY = yes;
    XFRM_IPTFS = yes;
    XFRM_ESPINTCP = yes;
    DIBS = yes;
    XDP_SOCKETS = yes;
    XDP_SOCKETS_DIAG = yes;
    INET = yes;
    IP_MULTICAST = yes;
    IP_ADVANCED_ROUTER = yes;
    IP_MULTIPLE_TABLES = yes;
    IP_ROUTE_MULTIPATH = yes;
    IP_ROUTE_VERBOSE = yes;
    IP_ROUTE_CLASSID = yes;
    NET_IPIP = yes;
    NET_IPGRE_DEMUX = yes;
    NET_IP_TUNNEL = yes;
    NET_IPGRE = yes;
    IP_MROUTE_COMMON = yes;
    IP_MROUTE = yes;
    IP_MROUTE_MULTIPLE_TABLES = yes;
    IP_PIMSM_V1 = yes;
    IP_PIMSM_V2 = yes;
    SYN_COOKIES = yes;
    NET_IPVTI = yes;
    NET_UDP_TUNNEL = yes;
    NET_FOU = yes;
    NET_FOU_IP_TUNNELS = yes;
    INET_AH = yes;
    INET_ESP = yes;
    INET_ESP_OFFLOAD = yes;
    INET_ESPINTCP = yes;
    INET_IPCOMP = yes;
    INET_TABLE_PERTURB_ORDER = freeform "16";
    INET_XFRM_TUNNEL = yes;
    INET_TUNNEL = yes;
    INET_DIAG = yes;
    INET_TCP_DIAG = yes;
    INET_UDP_DIAG = yes;
    INET_RAW_DIAG = yes;
    INET_DIAG_DESTROY = yes;
    TCP_CONG_ADVANCED = yes;
    TCP_CONG_BIC = yes;
    TCP_CONG_CUBIC = yes;
    TCP_CONG_WESTWOOD = yes;
    TCP_CONG_HTCP = yes;
    TCP_CONG_HSTCP = yes;
    TCP_CONG_HYBLA = yes;
    TCP_CONG_VEGAS = yes;
    TCP_CONG_NV = yes;
    TCP_CONG_SCALABLE = yes;
    TCP_CONG_LP = yes;
    TCP_CONG_VENO = yes;
    TCP_CONG_YEAH = yes;
    TCP_CONG_ILLINOIS = yes;
    TCP_CONG_DCTCP = yes;
    TCP_CONG_CDG = yes;
    TCP_CONG_BBR = yes;
    DEFAULT_CUBIC = yes;
    DEFAULT_TCP_CONG = freeform "cubic";
    TCP_MD5SIG = yes;
    IPV6 = yes;
    IPV6_ROUTER_PREF = yes;
    IPV6_ROUTE_INFO = yes;
    IPV6_OPTIMISTIC_DAD = yes;
    INET6_AH = yes;
    INET6_ESP = yes;
    INET6_ESP_OFFLOAD = yes;
    INET6_ESPINTCP = yes;
    INET6_IPCOMP = yes;
    IPV6_MIP6 = yes;
    IPV6_ILA = yes;
    INET6_XFRM_TUNNEL = yes;
    INET6_TUNNEL = yes;
    IPV6_VTI = yes;
    IPV6_SIT = yes;
    IPV6_NDISC_NODETYPE = yes;
    IPV6_TUNNEL = yes;
    IPV6_GRE = yes;
    IPV6_FOU = yes;
    IPV6_FOU_TUNNEL = yes;
    IPV6_MULTIPLE_TABLES = yes;
    IPV6_SUBTREES = yes;
    IPV6_MROUTE = yes;
    IPV6_MROUTE_MULTIPLE_TABLES = yes;
    IPV6_PIMSM_V2 = yes;
    IPV6_SEG6_LWTUNNEL = yes;
    IPV6_SEG6_HMAC = yes;
    IPV6_SEG6_BPF = yes;
    NETLABEL = yes;
    MPTCP = yes;
    INET_MPTCP_DIAG = yes;
    MPTCP_IPV6 = yes;
    NETWORK_SECMARK = yes;
    NET_PTP_CLASSIFY = yes;
    NETFILTER = yes;
    NETFILTER_ADVANCED = yes;
    BRIDGE_NETFILTER = yes;
    NETFILTER_INGRESS = yes;
    NETFILTER_EGRESS = yes;
    NETFILTER_SKIP_EGRESS = yes;
    NETFILTER_NETLINK = yes;
    NETFILTER_FAMILY_BRIDGE = yes;
    NETFILTER_FAMILY_ARP = yes;
    NETFILTER_BPF_LINK = yes;
    NETFILTER_NETLINK_HOOK = yes;
    NETFILTER_NETLINK_ACCT = yes;
    NETFILTER_NETLINK_QUEUE = yes;
    NETFILTER_NETLINK_LOG = yes;
    NETFILTER_NETLINK_OSF = yes;
    NF_CONNTRACK = yes;
    NF_LOG_SYSLOG = yes;
    NETFILTER_CONNCOUNT = yes;
    NF_CONNTRACK_MARK = yes;
    NF_CONNTRACK_SECMARK = yes;
    NF_CONNTRACK_ZONES = yes;
    NF_CONNTRACK_PROCFS = yes;
    NF_CONNTRACK_EVENTS = yes;
    NF_CONNTRACK_TIMEOUT = yes;
    NF_CONNTRACK_TIMESTAMP = yes;
    NF_CONNTRACK_LABELS = yes;
    NF_CONNTRACK_OVS = yes;
    NF_CT_PROTO_GRE = yes;
    NF_CT_PROTO_SCTP = yes;
    NF_CT_PROTO_UDPLITE = yes;
    NF_CONNTRACK_AMANDA = yes;
    NF_CONNTRACK_FTP = yes;
    NF_CONNTRACK_H323 = yes;
    NF_CONNTRACK_IRC = yes;
    NF_CONNTRACK_BROADCAST = yes;
    NF_CONNTRACK_NETBIOS_NS = yes;
    NF_CONNTRACK_SNMP = yes;
    NF_CONNTRACK_PPTP = yes;
    NF_CONNTRACK_SANE = yes;
    NF_CONNTRACK_SIP = yes;
    NF_CONNTRACK_TFTP = yes;
    NF_CT_NETLINK = yes;
    NF_CT_NETLINK_TIMEOUT = yes;
    NF_CT_NETLINK_HELPER = yes;
    NETFILTER_NETLINK_GLUE_CT = yes;
    NF_NAT = yes;
    NF_NAT_AMANDA = yes;
    NF_NAT_FTP = yes;
    NF_NAT_IRC = yes;
    NF_NAT_SIP = yes;
    NF_NAT_TFTP = yes;
    NF_NAT_REDIRECT = yes;
    NF_NAT_MASQUERADE = yes;
    NF_NAT_OVS = yes;
    NETFILTER_SYNPROXY = yes;
    NF_TABLES = yes;
    NF_TABLES_INET = yes;
    NF_TABLES_NETDEV = yes;
    NFT_NUMGEN = yes;
    NFT_CT = yes;
    NFT_FLOW_OFFLOAD = yes;
    NFT_CONNLIMIT = yes;
    NFT_LOG = yes;
    NFT_LIMIT = yes;
    NFT_MASQ = yes;
    NFT_REDIR = yes;
    NFT_NAT = yes;
    NFT_TUNNEL = yes;
    NFT_QUEUE = yes;
    NFT_QUOTA = yes;
    NFT_REJECT = yes;
    NFT_REJECT_INET = yes;
    NFT_COMPAT = yes;
    NFT_HASH = yes;
    NFT_FIB = yes;
    NFT_FIB_INET = yes;
    NFT_XFRM = yes;
    NFT_SOCKET = yes;
    NFT_OSF = yes;
    NFT_TPROXY = yes;
    NFT_SYNPROXY = yes;
    NF_DUP_NETDEV = yes;
    NFT_DUP_NETDEV = yes;
    NFT_FWD_NETDEV = yes;
    NFT_FIB_NETDEV = yes;
    NFT_REJECT_NETDEV = yes;
    NF_FLOW_TABLE_INET = yes;
    NF_FLOW_TABLE = yes;
    NF_FLOW_TABLE_PROCFS = yes;
    NETFILTER_XTABLES = yes;
    NETFILTER_XT_MARK = yes;
    NETFILTER_XT_CONNMARK = yes;
    NETFILTER_XT_SET = yes;
    NETFILTER_XT_TARGET_AUDIT = yes;
    NETFILTER_XT_TARGET_CHECKSUM = yes;
    NETFILTER_XT_TARGET_CLASSIFY = yes;
    NETFILTER_XT_TARGET_CONNMARK = yes;
    NETFILTER_XT_TARGET_CONNSECMARK = yes;
    NETFILTER_XT_TARGET_CT = yes;
    NETFILTER_XT_TARGET_DSCP = yes;
    NETFILTER_XT_TARGET_HL = yes;
    NETFILTER_XT_TARGET_HMARK = yes;
    NETFILTER_XT_TARGET_IDLETIMER = yes;
    NETFILTER_XT_TARGET_LED = yes;
    NETFILTER_XT_TARGET_LOG = yes;
    NETFILTER_XT_TARGET_MARK = yes;
    NETFILTER_XT_NAT = yes;
    NETFILTER_XT_TARGET_NETMAP = yes;
    NETFILTER_XT_TARGET_NFLOG = yes;
    NETFILTER_XT_TARGET_NFQUEUE = yes;
    NETFILTER_XT_TARGET_RATEEST = yes;
    NETFILTER_XT_TARGET_REDIRECT = yes;
    NETFILTER_XT_TARGET_MASQUERADE = yes;
    NETFILTER_XT_TARGET_TEE = yes;
    NETFILTER_XT_TARGET_TPROXY = yes;
    NETFILTER_XT_TARGET_SECMARK = yes;
    NETFILTER_XT_TARGET_TCPMSS = yes;
    NETFILTER_XT_TARGET_TCPOPTSTRIP = yes;
    NETFILTER_XT_MATCH_ADDRTYPE = yes;
    NETFILTER_XT_MATCH_BPF = yes;
    NETFILTER_XT_MATCH_CGROUP = yes;
    NETFILTER_XT_MATCH_CLUSTER = yes;
    NETFILTER_XT_MATCH_COMMENT = yes;
    NETFILTER_XT_MATCH_CONNBYTES = yes;
    NETFILTER_XT_MATCH_CONNLABEL = yes;
    NETFILTER_XT_MATCH_CONNLIMIT = yes;
    NETFILTER_XT_MATCH_CONNMARK = yes;
    NETFILTER_XT_MATCH_CONNTRACK = yes;
    NETFILTER_XT_MATCH_CPU = yes;
    NETFILTER_XT_MATCH_DCCP = yes;
    NETFILTER_XT_MATCH_DEVGROUP = yes;
    NETFILTER_XT_MATCH_DSCP = yes;
    NETFILTER_XT_MATCH_ECN = yes;
    NETFILTER_XT_MATCH_ESP = yes;
    NETFILTER_XT_MATCH_HASHLIMIT = yes;
    NETFILTER_XT_MATCH_HELPER = yes;
    NETFILTER_XT_MATCH_HL = yes;
    NETFILTER_XT_MATCH_IPCOMP = yes;
    NETFILTER_XT_MATCH_IPRANGE = yes;
    NETFILTER_XT_MATCH_IPVS = yes;
    NETFILTER_XT_MATCH_L2TP = yes;
    NETFILTER_XT_MATCH_LENGTH = yes;
    NETFILTER_XT_MATCH_LIMIT = yes;
    NETFILTER_XT_MATCH_MAC = yes;
    NETFILTER_XT_MATCH_MARK = yes;
    NETFILTER_XT_MATCH_MULTIPORT = yes;
    NETFILTER_XT_MATCH_NFACCT = yes;
    NETFILTER_XT_MATCH_OSF = yes;
    NETFILTER_XT_MATCH_OWNER = yes;
    NETFILTER_XT_MATCH_POLICY = yes;
    NETFILTER_XT_MATCH_PHYSDEV = yes;
    NETFILTER_XT_MATCH_PKTTYPE = yes;
    NETFILTER_XT_MATCH_QUOTA = yes;
    NETFILTER_XT_MATCH_RATEEST = yes;
    NETFILTER_XT_MATCH_REALM = yes;
    NETFILTER_XT_MATCH_RECENT = yes;
    NETFILTER_XT_MATCH_SCTP = yes;
    NETFILTER_XT_MATCH_SOCKET = yes;
    NETFILTER_XT_MATCH_STATE = yes;
    NETFILTER_XT_MATCH_STATISTIC = yes;
    NETFILTER_XT_MATCH_STRING = yes;
    NETFILTER_XT_MATCH_TCPMSS = yes;
    NETFILTER_XT_MATCH_TIME = yes;
    NETFILTER_XT_MATCH_U32 = yes;
    IP_SET = yes;
    IP_SET_MAX = freeform "2";
    IP_SET_BITMAP_IP = yes;
    IP_SET_BITMAP_IPMAC = yes;
    IP_SET_BITMAP_PORT = yes;
    IP_SET_HASH_IP = yes;
    IP_SET_HASH_IPMARK = yes;
    IP_SET_HASH_IPPORT = yes;
    IP_SET_HASH_IPPORTIP = yes;
    IP_SET_HASH_IPPORTNET = yes;
    IP_SET_HASH_IPMAC = yes;
    IP_SET_HASH_MAC = yes;
    IP_SET_HASH_NETPORTNET = yes;
    IP_SET_HASH_NET = yes;
    IP_SET_HASH_NETNET = yes;
    IP_SET_HASH_NETPORT = yes;
    IP_SET_HASH_NETIFACE = yes;
    IP_SET_LIST_SET = yes;
    IP_VS = yes;
    IP_VS_IPV6 = yes;
    IP_VS_TAB_BITS = freeform "12";
    IP_VS_PROTO_TCP = yes;
    IP_VS_PROTO_UDP = yes;
    IP_VS_PROTO_AH_ESP = yes;
    IP_VS_PROTO_ESP = yes;
    IP_VS_PROTO_AH = yes;
    IP_VS_RR = yes;
    IP_VS_WRR = yes;
    IP_VS_LC = yes;
    IP_VS_WLC = yes;
    IP_VS_FO = yes;
    IP_VS_OVF = yes;
    IP_VS_LBLC = yes;
    IP_VS_LBLCR = yes;
    IP_VS_DH = yes;
    IP_VS_SH = yes;
    IP_VS_MH = yes;
    IP_VS_SED = yes;
    IP_VS_NQ = yes;
    IP_VS_TWOS = yes;
    IP_VS_SH_TAB_BITS = freeform "8";
    IP_VS_MH_TAB_INDEX = freeform "12";
    IP_VS_FTP = yes;
    IP_VS_NFCT = yes;
    IP_VS_PE_SIP = yes;
    NF_DEFRAG_IPV4 = yes;
    NF_SOCKET_IPV4 = yes;
    NF_TPROXY_IPV4 = yes;
    NF_TABLES_IPV4 = yes;
    NFT_REJECT_IPV4 = yes;
    NFT_DUP_IPV4 = yes;
    NFT_FIB_IPV4 = yes;
    NF_TABLES_ARP = yes;
    NF_DUP_IPV4 = yes;
    NF_LOG_ARP = yes;
    NF_LOG_IPV4 = yes;
    NF_REJECT_IPV4 = yes;
    NF_NAT_SNMP_BASIC = yes;
    NF_NAT_PPTP = yes;
    NF_NAT_H323 = yes;
    IP_NF_IPTABLES = yes;
    IP_NF_MATCH_AH = yes;
    IP_NF_MATCH_ECN = yes;
    IP_NF_MATCH_RPFILTER = yes;
    IP_NF_MATCH_TTL = yes;
    IP_NF_TARGET_REJECT = yes;
    IP_NF_TARGET_SYNPROXY = yes;
    IP_NF_TARGET_ECN = yes;
    NFT_COMPAT_ARP = yes;
    IP_NF_ARP_MANGLE = yes;
    NF_SOCKET_IPV6 = yes;
    NF_TPROXY_IPV6 = yes;
    NF_TABLES_IPV6 = yes;
    NFT_REJECT_IPV6 = yes;
    NFT_DUP_IPV6 = yes;
    NFT_FIB_IPV6 = yes;
    NF_DUP_IPV6 = yes;
    NF_REJECT_IPV6 = yes;
    NF_LOG_IPV6 = yes;
    IP6_NF_IPTABLES = yes;
    IP6_NF_MATCH_AH = yes;
    IP6_NF_MATCH_EUI64 = yes;
    IP6_NF_MATCH_FRAG = yes;
    IP6_NF_MATCH_OPTS = yes;
    IP6_NF_MATCH_HL = yes;
    IP6_NF_MATCH_IPV6HEADER = yes;
    IP6_NF_MATCH_MH = yes;
    IP6_NF_MATCH_RPFILTER = yes;
    IP6_NF_MATCH_RT = yes;
    IP6_NF_MATCH_SRH = yes;
    IP6_NF_TARGET_REJECT = yes;
    IP6_NF_TARGET_SYNPROXY = yes;
    IP6_NF_TARGET_NPT = yes;
    NF_DEFRAG_IPV6 = yes;
    NF_TABLES_BRIDGE = yes;
    NFT_BRIDGE_META = yes;
    NFT_BRIDGE_REJECT = yes;
    NF_CONNTRACK_BRIDGE = yes;
    BRIDGE_NF_EBTABLES = yes;
    BRIDGE_EBT_802_3 = yes;
    BRIDGE_EBT_AMONG = yes;
    BRIDGE_EBT_ARP = yes;
    BRIDGE_EBT_IP = yes;
    BRIDGE_EBT_IP6 = yes;
    BRIDGE_EBT_LIMIT = yes;
    BRIDGE_EBT_MARK = yes;
    BRIDGE_EBT_PKTTYPE = yes;
    BRIDGE_EBT_STP = yes;
    BRIDGE_EBT_VLAN = yes;
    BRIDGE_EBT_ARPREPLY = yes;
    BRIDGE_EBT_DNAT = yes;
    BRIDGE_EBT_MARK_T = yes;
    BRIDGE_EBT_REDIRECT = yes;
    BRIDGE_EBT_SNAT = yes;
    BRIDGE_EBT_LOG = yes;
    BRIDGE_EBT_NFLOG = yes;
    IP_SCTP = yes;
    SCTP_DEFAULT_COOKIE_HMAC_SHA256 = yes;
    INET_SCTP_DIAG = yes;
    RDS = yes;
    RDS_TCP = yes;
    TIPC = yes;
    TIPC_MEDIA_UDP = yes;
    TIPC_CRYPTO = yes;
    TIPC_DIAG = yes;
    ATM = yes;
    ATM_CLIP = yes;
    ATM_LANE = yes;
    ATM_MPOA = yes;
    ATM_BR2684 = yes;
    L2TP = yes;
    L2TP_DEBUGFS = yes;
    L2TP_V3 = yes;
    L2TP_IP = yes;
    L2TP_ETH = yes;
    STP = yes;
    BRIDGE = yes;
    BRIDGE_IGMP_SNOOPING = yes;
    BRIDGE_VLAN_FILTERING = yes;
    NET_DSA = yes;
    NET_DSA_TAG_NONE = yes;
    NET_DSA_TAG_AR9331 = yes;
    NET_DSA_TAG_BRCM_COMMON = yes;
    NET_DSA_TAG_BRCM = yes;
    NET_DSA_TAG_BRCM_LEGACY = yes;
    NET_DSA_TAG_BRCM_LEGACY_FCS = yes;
    NET_DSA_TAG_BRCM_PREPEND = yes;
    NET_DSA_TAG_HELLCREEK = yes;
    NET_DSA_TAG_GSWIP = yes;
    NET_DSA_TAG_DSA_COMMON = yes;
    NET_DSA_TAG_DSA = yes;
    NET_DSA_TAG_EDSA = yes;
    NET_DSA_TAG_MTK = yes;
    NET_DSA_TAG_MXL_GSW1XX = yes;
    NET_DSA_TAG_KSZ = yes;
    NET_DSA_TAG_OCELOT = yes;
    NET_DSA_TAG_OCELOT_8021Q = yes;
    NET_DSA_TAG_QCA = yes;
    NET_DSA_TAG_RTL4_A = yes;
    NET_DSA_TAG_RTL8_4 = yes;
    NET_DSA_TAG_RZN1_A5PSW = yes;
    NET_DSA_TAG_LAN9303 = yes;
    NET_DSA_TAG_SJA1105 = yes;
    NET_DSA_TAG_TRAILER = yes;
    NET_DSA_TAG_VSC73XX_8021Q = yes;
    NET_DSA_TAG_XRS700X = yes;
    NET_DSA_TAG_YT921X = yes;
    VLAN_8021Q = yes;
    LLC = yes;
    LLC2 = yes;
    ATALK = yes;
    X25 = yes;
    LAPB = yes;
    PHONET = yes;
    "6LOWPAN" = yes;
    "6LOWPAN_NHC" = yes;
    "6LOWPAN_NHC_DEST" = yes;
    "6LOWPAN_NHC_FRAGMENT" = yes;
    "6LOWPAN_NHC_HOP" = yes;
    "6LOWPAN_NHC_IPV6" = yes;
    "6LOWPAN_NHC_MOBILITY" = yes;
    "6LOWPAN_NHC_ROUTING" = yes;
    "6LOWPAN_NHC_UDP" = yes;
    "6LOWPAN_GHC_EXT_HDR_HOP" = yes;
    "6LOWPAN_GHC_UDP" = yes;
    "6LOWPAN_GHC_ICMPV6" = yes;
    "6LOWPAN_GHC_EXT_HDR_DEST" = yes;
    "6LOWPAN_GHC_EXT_HDR_FRAG" = yes;
    "6LOWPAN_GHC_EXT_HDR_ROUTE" = yes;
    IEEE802154 = yes;
    IEEE802154_SOCKET = yes;
    IEEE802154_6LOWPAN = yes;
    MAC802154 = yes;
    NET_SCHED = yes;
    NET_SCH_HTB = yes;
    NET_SCH_HFSC = yes;
    NET_SCH_PRIO = yes;
    NET_SCH_MULTIQ = yes;
    NET_SCH_RED = yes;
    NET_SCH_SFB = yes;
    NET_SCH_SFQ = yes;
    NET_SCH_TEQL = yes;
    NET_SCH_TBF = yes;
    NET_SCH_CBS = yes;
    NET_SCH_ETF = yes;
    NET_SCH_MQPRIO_LIB = yes;
    NET_SCH_TAPRIO = yes;
    NET_SCH_GRED = yes;
    NET_SCH_NETEM = yes;
    NET_SCH_DRR = yes;
    NET_SCH_MQPRIO = yes;
    NET_SCH_SKBPRIO = yes;
    NET_SCH_CHOKE = yes;
    NET_SCH_QFQ = yes;
    NET_SCH_CODEL = yes;
    NET_SCH_FQ_CODEL = yes;
    NET_SCH_CAKE = yes;
    NET_SCH_FQ = yes;
    NET_SCH_HHF = yes;
    NET_SCH_PIE = yes;
    NET_SCH_FQ_PIE = yes;
    NET_SCH_INGRESS = yes;
    NET_SCH_PLUG = yes;
    NET_SCH_ETS = yes;
    NET_SCH_DUALPI2 = yes;
    NET_CLS = yes;
    NET_CLS_BASIC = yes;
    NET_CLS_ROUTE4 = yes;
    NET_CLS_FW = yes;
    NET_CLS_U32 = yes;
    CLS_U32_PERF = yes;
    CLS_U32_MARK = yes;
    NET_CLS_FLOW = yes;
    NET_CLS_CGROUP = yes;
    NET_CLS_BPF = yes;
    NET_CLS_FLOWER = yes;
    NET_CLS_MATCHALL = yes;
    NET_EMATCH = yes;
    NET_EMATCH_STACK = freeform "32";
    NET_EMATCH_CMP = yes;
    NET_EMATCH_NBYTE = yes;
    NET_EMATCH_U32 = yes;
    NET_EMATCH_META = yes;
    NET_EMATCH_TEXT = yes;
    NET_EMATCH_IPSET = yes;
    NET_EMATCH_IPT = yes;
    NET_CLS_ACT = yes;
    NET_ACT_POLICE = yes;
    NET_ACT_GACT = yes;
    NET_ACT_MIRRED = yes;
    NET_ACT_NAT = yes;
    NET_ACT_PEDIT = yes;
    NET_ACT_SIMP = yes;
    NET_ACT_SKBEDIT = yes;
    NET_ACT_CSUM = yes;
    NET_ACT_MPLS = yes;
    NET_ACT_VLAN = yes;
    NET_ACT_BPF = yes;
    NET_ACT_CONNMARK = yes;
    NET_ACT_CTINFO = yes;
    NET_ACT_SKBMOD = yes;
    NET_ACT_TUNNEL_KEY = yes;
    NET_ACT_CT = yes;
    NET_ACT_GATE = yes;
    NET_SCH_FIFO = yes;
    DCB = yes;
    DNS_RESOLVER = yes;
    BATMAN_ADV = yes;
    BATMAN_ADV_BATMAN_V = yes;
    BATMAN_ADV_BLA = yes;
    BATMAN_ADV_DAT = yes;
    BATMAN_ADV_MCAST = yes;
    OPENVSWITCH = yes;
    OPENVSWITCH_GRE = yes;
    VSOCKETS = yes;
    VSOCKETS_DIAG = yes;
    VSOCKETS_LOOPBACK = yes;
    VIRTIO_VSOCKETS = yes;
    VIRTIO_VSOCKETS_COMMON = yes;
    NETLINK_DIAG = yes;
    MPLS = yes;
    NET_MPLS_GSO = yes;
    MPLS_ROUTING = yes;
    MPLS_IPTUNNEL = yes;
    NET_NSH = yes;
    HSR = yes;
    NET_SWITCHDEV = yes;
    NET_L3_MASTER_DEV = yes;
    QRTR = yes;
    QRTR_TUN = yes;

    # FRAMEBUFFER_CONSOLE = no;
    # FRAMEBUFFER_CONSOLE_DEFERRED_TAKEOVER = unset;
    # FRAMEBUFFER_CONSOLE_DETECT_PRIMARY = unset;
    # FRAMEBUFFER_CONSOLE_ROTATION = unset;
    # VT = no;

  };

  moreConfig = lib.attrsets.mapAttrs
    (k: v: lib.mkForce v)
    _moreConfig;
    
  structuredExtraConfig = moreConfig;
in
buildLinux (args // {
  inherit version;
  modDirVersion = version;
  src = builtins.fetchGit /var/stuff/foss/tip;
  extraMeta.branch = "drm-tip";

  defconfig = "defconfig";
  autoModules = false;
  enableCommonConfig = false;
  inherit structuredExtraConfig;
} // (args.argsOverride or {}))
